# NumPy Arrays 1D & 2D

In [2]:
import numpy as np

a = [1, 2, 3]
b = np.array(a)

print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1, 2, 3, '5', 4, 5]
b = np.array(a, dtype = str)
print(b)

['1' '2' '3' '5' '4' '5']


In [4]:
a = [1, 2, 3, '5', 4, 5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4' '5' '1' '2' '3' '5' '4' '5' '1' '2' '3' '5' '4' '5']


### np zeros

In [5]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [7]:
b = np.zeros((2, 3), dtype = int)
print(b)

c = np.zeros((2, 3))
print(c)


[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]


### np ones

In [6]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

### np full

In [12]:
b = np.full((2, 3), 5, dtype = float)
print(b)

c = np.full((2, 3), 5)
print(c)

[[5. 5. 5.]
 [5. 5. 5.]]
[[5 5 5]
 [5 5 5]]


np empty Regresa un array sin inicializar con valores aleatorios

In [14]:
b = np.empty((2, 3))
print(b)

c = np.empty((2, 3))
print(c)

[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]
[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]


## Numpy 2D

### np.arange

In [16]:
b = np.arange(2, 20, 2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### np.linspace 
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]

Return evenly spaced numbers over a specified interval.
Returns num evenly spaced samples, calculated over the interval [start, stop].

In [24]:
b = np.linspace(2, 10, num = 4)
print(b)
print(b[1] - b[0])
print(b[3] - b[2])


[ 2.          4.66666667  7.33333333 10.        ]
2.666666666666666
2.666666666666667


### np.identity

In [25]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.eye

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)[source]


Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [26]:
b = np.eye(3, 4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### np.random.rand

In [27]:
b = np.random.rand(3)
b

array([0.5599841 , 0.02991516, 0.97522483])

### np.random.rand


In [31]:
a = np.random.rand(3)
print(a)
b = np.random.rand(2, 3)
print(b)

[0.2818014  0.56326358 0.09678695]
[[0.95770222 0.74415119 0.8105432 ]
 [0.0868493  0.12907773 0.3541841 ]]


In [32]:
b = np.random.rand(10)*10
print(b)

[3.62729942 2.67094574 9.37511014 9.2091678  1.7834752  2.58625576
 0.81401443 0.61896808 8.77108762 5.64543825]


### np.random.randint

random.randint(low, high=None, size=None, dtype=int)

Return random integers from low (inclusive) to high (exclusive).
Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [29]:
a = np.random.rand(3)
print(b)
b = np.random.rand(2, 3)
print(ab)

array([[0.05684248, 0.48540928, 0.95903838],
       [0.79646391, 0.06927303, 0.05981643]])

In [33]:
np.random.randint(5, size=(2, 4))

array([[1, 1, 1, 2],
       [3, 0, 4, 4]])

Random Integer array

Syntax for creating a random integer array ranging from 0 to 10 of size (4, 4)

In [35]:
b = np.random.randint(5, size=(2, 4))
print(b)

[[0 2 1 1]
 [4 2 1 1]]


NumPy Inclusive

Problem Statement:
Create an array with values ranging consecutively from 9 to 49 (both inclusive).
Print the Numpy array.

Output Format :
element1 element2 element3 ...

In [1]:
import numpy as np

start = 9
stop = 49
step = 1
arr = np.arange(start, stop+1, step)

for i in arr:
    print(i, end = ' ')


9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

Identity Matrix

Problem Statement:
Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).
Print the Numpy array.

Output Format :
numpyArray

In [2]:
import numpy as np


m = np.eye(5, 6, dtype=int)
print(m)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


Cut the Rope

Problem Statement:
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.

Output Format :
element1 
element2 
element3

In [10]:
import numpy as np
arr_9pts = np.linspace(0, 5, 9, endpoint = False)
print(arr_9pts)
arr_9pts = arr_9pts[1:]
arr_round = np.around(arr_9pts, 2)
for i in arr_round:
    print(i, end = ' ')

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444]
0.56 1.11 1.67 2.22 2.78 3.33 3.89 4.44 

## Slicing and Indexing

In [12]:
import numpy  as np
 
li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [13]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)


(5,)
int64
(8,)


In [19]:
print(li[3])
print(arr[3])
print(li[1:4])
print(arr[1:4])

4
4
[2, 3, 4]
[2 3 4]


In [15]:
li_2d = [[1,2,3,4],[5,6,7, 8],[9,10,11,12], [13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [16]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)


(4, 4)
int64
(32, 8)


In [22]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2, 1])


10
10
10


In [23]:
print(li_2d[1][:3])

[5, 6, 7]


In [24]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [25]:
print(li_2d[1][:3])
print(arr_2d[1, :3])
print(li_2d[0:3][2])

[5, 6, 7]
[5 6 7]
[9, 10, 11, 12]


In [26]:
x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [27]:
print(li_2d[0:3][0])
print(arr_2d[0:3, 2])

[1, 2, 3, 4]
[ 3  7 11]


In [28]:
print(arr_2d[2:4, 1:3])
print(li_2d[2:4][1:3]) #FALLA

[[10 11]
 [14 15]]
[[13, 14, 15, 16]]


Print Elements

Problem Statement:
Given a 2D integer array size (4, 5) with name input_?
Print elements of highlighted matrix

Output Format :
element1 element2 element3 . . .
element1 element2 element3 . . .
element1 element2 element3 . . .
element1 element2 element3 . . .

In [30]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
print(input)

<bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x7f437f5378b0>>


In [90]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

def print_enum3(arr):
    s = np.shape(arr)
    if(len(s) == 1):
        for i in arr :
            print(i, end = ' ')
        print()
    else :
        for i in arr:
            for j in i:
                print(j, end = ' ')
        print()
    

print_enum3(input_[2,0:3])
print_enum3(input_[1:,3])
print_enum3(input_[2:])
print_enum3(input_[1:3, 1:3])


11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 


## Mathematical Operations 1D

In [92]:
import numpy as np

li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)


[1, 2, 3, 4, 5]
[ 9  3  1 19  5]
[ 3 18  5 18  2]


In [93]:
li = [i + 1 for i  in li]
li

[2, 3, 4, 5, 6]

In [94]:
a = a + 1
a

array([10,  4,  2, 20,  6])

In [96]:
c = a + b
c

array([13, 22,  7, 38,  8])

In [97]:
d = a - b
d

array([  7, -14,  -3,   2,   4])

In [98]:
e = a * b
e

array([ 30,  72,  10, 360,  12])

In [99]:
f = a / b
f

array([3.33333333, 0.22222222, 0.4       , 1.11111111, 3.        ])

In [100]:
g = a // b
g

array([3, 0, 0, 1, 3])

In [101]:
h = a ** b
h

array([                1000,          68719476736,                   32,
       -2680031486438014976,                   36])

## Boolean Indexing - 1D

In [1]:
import numpy as np
a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[16  2 18  4 19  7  2 12]


In [2]:
print(b > 10)

[ True False  True False  True False False  True]


In [3]:
bool_arr = b> 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[ True False  True False  True False False  True]
[16 18 19 12]


In [4]:
new_arr = b[b > 10]
new_arr

array([16, 18, 19, 12])

In [8]:
new_arr = b[(b > 10) & (b < 18)]
new_arr

array([16, 12])

In [11]:
print(b) 
c = b
c

[16  2 18  4 19  7  2 12]


array([16,  2, 18,  4, 19,  7,  2, 12])

In [14]:
c[:3] = 19
print(c)
c[c > 15] = 100
print(c)

[ 19  19  19   4 100   7   2  12]
[100 100 100   4 100   7   2  12]


In [17]:
print(b)
print(b[b == 100])
ind = np.where(b == 100)
print(ind)


[100 100 100   4 100   7   2  12]
[100 100 100 100]
(array([0, 1, 2, 4]),)


In [20]:
print(a)
print(b)
ind = np.where(b == 100)
print(ind)
print(a[ind])

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100   4 100   7   2  12]
(array([0, 1, 2, 4]),)
['t' 'b' 'r' 'e']


Non-Zero elements

Problem Statemnt:
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.
Output Format :
index1 index2 index3 ... 

In [37]:
arr = np.array([1, 2, 0, 0, 4, 0])
idx = np.where(arr != 0)
for i in idx: 
    print(*i, end = ' ')

0 1 4 

Multiples of 3

Problem Statement:
Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
Print the index of elements.
Output Format :
index1 index2 index3 ... 

In [44]:
arr = np.arange(1, 20, 2)
print(arr)
idx = np.where(arr % 3 == 0)
for i in idx: 
    print(*i, end = ' ')


[ 1  3  5  7  9 11 13 15 17 19]
1 4 7 

Odd elements

Problem Statemnt:
Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.
Output Format :
firstElement secondElement  ... 

In [50]:
arr = np.arange(1, 11)
odd_list = arr % 2 != 0
arr[odd_list] = -1
print(*arr)


-1 2 -1 4 -1 6 -1 8 -1 10


Replace Max

Problem Statemnt:
Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
Note: Generate the following array
array([11, 2, 13, 4, 15, 6, 27, 8, 19])
Print the Numpy array.
Output Format :
firstElement
secondElement 
... 

In [82]:
a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
print(a)
idx = np.where(a == a.max())
a[idx[0]] = -1
print(a)


[11  2 13  4 15  6 27  8 19]
[11  2 13  4 15  6 -1  8 19]


Negate Elements

Problem Statemnt:
Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.
Output Format :
firstElement 
secondElement  
... 

In [103]:
arr = np.arange(1, 11)
print(arr)
idx = np.where((arr >= 3) & (arr <= 8), arr*-1, arr)
print(*idx)


[ 1  2  3  4  5  6  7  8  9 10]
1 2 -3 -4 -5 -6 -7 -8 9 10


Height

Problem Statemnt:
Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
Print the Numpy array.

Output Format :
age1 height1 
age2 height2 

In [124]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

idx = np.where(height > 155)[0]

for i in idx:
    print(age[i],' ', height[i], end = ' ')


15   156 19   180 20   162 21   157 22   158 23   179 16   182 18   183 20   159 15   160 17   172 

## Boolean Indexing

In [150]:
import numpy as np
a = np.random.randint(1, 30, (5, 6))
print(a)

[[ 6 20  6 20  3 29]
 [ 8  8 29 14  2 29]
 [16 17 16  8 14 20]
 [29 25 27 25 28 20]
 [12 13 25 13 12  3]]


In [151]:
bool_arr = a > 20
print(bool_arr)

[[False False False False False  True]
 [False False  True False False  True]
 [False False False False False False]
 [ True  True  True  True  True False]
 [False False  True False False False]]


In [152]:
ans = a[bool_arr]
print(ans)

[29 29 29 29 25 27 25 28 25]


In [155]:
b = a
print(b)

[[ 6 20  6 20  3 29]
 [ 8  8 29 14  2 29]
 [16 17 16  8 14 20]
 [29 25 27 25 28 20]
 [12 13 25 13 12  3]]


In [156]:
b[bool_arr] = 100
print(b)

[[  6  20   6  20   3 100]
 [  8   8 100  14   2 100]
 [ 16  17  16   8  14  20]
 [100 100 100 100 100  20]
 [ 12  13 100  13  12   3]]


In [157]:
c = np.random.randint(1, 10, (2, 2))
print(c)

[[9 5]
 [8 9]]


In [158]:
c_bool = np.array([[True, False], [False, True], [True, True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [160]:
/print(c[c_bool])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [161]:
bool_arr = b[:, 3] == 100
print(bool_arr)

[False False False  True False]


In [162]:
b[bool_arr, 3] = 99
print(b)

[[  6  20   6  20   3 100]
 [  8   8 100  14   2 100]
 [ 16  17  16   8  14  20]
 [100 100 100  99 100  20]
 [ 12  13 100  13  12   3]]


## Numpy Broadcasting

In [163]:
import numpy as np

x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))
print(x)
print(y)

[[8 5 4]
 [9 9 2]
 [6 4 6]]
[[4 4 7]
 [1 8 6]
 [9 6 9]]


In [164]:
ans = x - y
print(ans)

[[ 4  1 -3]
 [ 8  1 -4]
 [-3 -2 -3]]


In [165]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3))
print(x)
print(y)

[[2 1 9]
 [4 9 9]
 [3 2 2]]
[5 1 3]


In [166]:
ans = x - y
print(ans)

[[-3  0  6]
 [-1  8  6]
 [-2  1 -1]]


In [167]:
x = np.random.randint(1, 10, (3, 2))
y = np.random.randint(1, 10, (2, 3))
print(x)
print(y)

[[3 6]
 [1 6]
 [5 9]]
[[7 1 8]
 [1 4 9]]


In [170]:
ans = x -y
print(ans)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [171]:
y = np.transpose(y)
print(y)
ans = x - y
print(ans)

[[7 1]
 [1 4]
 [8 9]]
[[-4  5]
 [ 0  2]
 [-3  0]]


Sort by column

Problem Statemnt:
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
 [[21 20 19 18 17]
  [16 15 14 13 12]
  [11 10  9  8  7]
  [ 6  5  4  3  2]]
Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1.
Output Format :
[[ 6  5  4  3  2]
[11 10  9  8  7]
[16 15 14 13 12]
[21 20 19 18 17]]

In [194]:
import numpy as np
#matrix = np.random.randint(1, 20, (4, 5))
matrix = np.array([[21, 20, 19, 18, 17], [16, 15, 14, 13, 12], [11, 10,  9,  8,  7], [ 6,  5,  4, 3, 2]])
print(matrix)
print(matrix[:, 1])

res = np.argsort(matrix[:, 1])
print(res)
print(matrix[res])

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]
[20 15 10  5]
[3 2 1 0]
[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [189]:
import numpy as np

arr = np.array([[3, 2], [1, 4], [2, 3]])
sorted_indices = np.argsort(arr[:, 1])
sorted_arr = arr[sorted_indices]

print(sorted_arr)


[[3 2]
 [2 3]
 [1 4]]


## Example

In [175]:
import  numpy  as np
import csv

file_obj = open('Datasets/Sample.csv')
data = csv.DictReader(file_obj, skipinitialspace = True)

killed = []
wounded = []
country = []

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])

np_killed = np.array(killed)
np_wounded = np.array(wounded)

np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'

np_killed = np.array(np_killed, dtype = float)
np_wounded = np.array(np_wounded, dtype = float)

killed_wounded = np_killed + np_wounded
np_country = np.array(country)

bool_arr = np_country == 'India'
ans = killed_wounded[bool_arr]
print(np.sum(ans))
print(np.sum(killed_wounded))

1167.0
51372.0


Killed in USA

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find value of killed column only where country == ‘United States’?
Print 0 in place of missing values.
Print count of Killed as integer value.
Output Format :
Killed1
Killed2
Killed3
Killed4

In [ ]:
import  numpy  as np
import csv

file_obj = open('Datasets/Sample.csv')
data = csv.DictReader(file_obj, skipinitialspace = True)

print(data)

killed = []
wounded = []
country = []

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)

np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'
np_country = np.array(country)

idx_USA = np_country == 'United States'
print(idx_USA)
print(*np_killed[idx_USA].astype(float).astype(int))

result = np_killed[idx_USA].astype(float).astype(int)
for i in result:
    print(i)


Total Killed in USA

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find total number of people killed from USA?
Note: Some columns of killed are empty so replace them by 0.
Print count of Killed as integer value.
Output Format :
TotalKilled

In [4]:
import  numpy  as np
import csv

file_obj = open('Datasets/Sample.csv')
data = csv.DictReader(file_obj, skipinitialspace = True)

print(data)

killed = []
wounded = []
country = []

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)

np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'
np_country = np.array(country)

idx_USA = np_country == 'United States'
print(idx_USA)
print(*np_killed[idx_USA].astype(float).astype(int))

result = np.sum(np_killed[idx_USA].astype(float).astype(int))
print(result)



[False False False ... False False False]
0 5 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 3 0 0 0 0 0 2 0 1 2 0 0 0 0 0 1 0 0 2 0 0 0 0 0 0 1 0 0 1 1 1 59 0 0 0 0 8 0 0 0 3 0 0 1
95


Terrorism Day

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)
Print count of NumberOFAttack as integer value.
Output Format :
count

In [14]:
import  numpy  as np
import csv

file_obj = open('Datasets/Sample.csv')
data = csv.DictReader(file_obj, skipinitialspace = True)

day = []


for row in data:
    day.append(row['Day'])

#print(day)
np_day = np.array(day).astype(float).astype(int)
print(np.sum(np_day[(np_day>= 10) & (np_day <= 20)]))
print(np.count_nonzero(np_day[(np_day>= 10) & (np_day <= 20)]))


60345
4002


Terrorism Date

Problem Statement :
Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
Note Ignore the case where day is 0
Print count of NumberOFAttack as integer value.

Output Format :
count

Usando str

In [44]:
import  numpy  as np
import csv

file_obj = open('Datasets/Sample.csv')
data = csv.DictReader(file_obj, skipinitialspace = True)

day = []
month = []
year = []
date = []

for row in data:
    day.append(row['Day'].zfill(2))
    month.append(row['Month'].zfill(2))
    year.append(row['Year'])

date = [f"{y}-{m}-{d}" for y, m, d in zip(year,month, day)]
dates = np.array(date, dtype='datetime64')
print(dates)



['2017-01-02' '2017-01-03' '2017-01-01' ... '2017-12-31' '2017-12-31'
 '2017-12-31']


Usando int

In [42]:
import numpy as np

day = ['1', '2', '3', '4']
month = ['1', '2', '3', '4']


dates = [f"2022-{int(m):02d}-{int(d):02d}" for m, d in zip(month, day)]

# Convierte los formatos de fecha en un tipo numpy.datetime64
dates = np.array(dates, dtype='datetime64')
print(dates)



['2022-01-01' '2022-02-02' '2022-03-03' '2022-04-04']


Ejemplo

In [ ]:
import  numpy  as np
import csv

file_obj = open('Datasets/Sample.csv')
data = csv.DictReader(file_obj, skipinitialspace = True)

day = []
month = []
year = []

for row in data:
    day.append(row['Day'])
    month.append(row['Month'])
    year.append(row['Year'])


dates = [f"{int(y)}-{int(m):02d}-{int(d):02d}" for y, m, d in zip(year, month, day)]

# Convierte los formatos de fecha en un tipo numpy.datetime64
np_dates = np.array(dates, dtype='datetime64')

dateStart = np.datetime64('2010-01-01')
dateEnd = np.datetime64('2017-01-31')

# np_dates_result = np_dates[np_dates == dateStart]

np_dates = np_dates[(np_dates>=dateStart)]
np_dates = np_dates[(np_dates<=dateEnd)]

print(np_dates)

Solucion

In [68]:

import  numpy  as np
import csv

file_obj = open('Datasets/Sample.csv')
data = csv.DictReader(file_obj, skipinitialspace = True)

day = []
month = []
year = []

for row in data:
    day.append(row['Day'])
    month.append(row['Month'])
    year.append(row['Year'])


list_dates = [f"{int(y)}-{int(m):02d}-{int(d):02d}" for y, m, d in zip(year, month, day)]

dates = []
for i in list_dates:
    if '00' in i:
        continue
    dates.append(i)
    
# Convierte los formatos de fecha en un tipo numpy.datetime64
np_dates = np.array(dates, dtype='datetime64')

dateStart = np.datetime64('2010-01-01')
dateEnd = np.datetime64('2010-01-31')

# np_dates_result = np_dates[np_dates == dateStart]
np_dates = np_dates[(np_dates>=dateStart)]
np_dates = np_dates[(np_dates<=dateEnd)]

print(np.count_nonzero(np_dates))

271


Terror Casualty Attack

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

Problem Statement :
As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.
In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.
So find out the attack in this period in which maximum casualties happened.
Print the count of casualties (as integer), city in which that attack happened and name of attack group.
Note : Casualty = Killed + Wounded.Fill the empty value in killed or wounded feature to 0.
Output Format :
Casualty City TerroristGroup


In [91]:

import  numpy  as np
import csv

casualty=[]
month=[]
city=[]

with open('Datasets/Sample.csv', 'r', encoding='utf-8') as data:
    reader = csv.DictReader(data)
    for row in reader:
        if row['State']=='Jammu and Kashmir' and row['Year']=='1999':
            if row['Month']=='5' or row['Month'] == 6 or row['Month'] == 7:
                city.append([row['City'], row['Group']])
                casualty.append([row['Killed'], row['Wounded']])

npcasualty=np.array(casualty)
npcity=np.array(city)
npcasualty[npcasualty=='']=0
npcasualty=np.array(npcasualty,dtype=float)
npcasualty=np.sum(npcasualty,axis=1)
index=np.argmax(npcasualty)
print(int(npcasualty[index]),npcity[index][0],npcity[index][1])





22 Kargil District Separatists


Terror Casualty Red

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.
Note: Casualty=Killed +Wounded
Print count of Casualty as integer value.
Output Format :
Count

In [98]:
import  numpy  as np
import csv

casualty=[]
month=[]
city=[]

with open('Datasets/Sample.csv', 'r', encoding='utf-8') as data:
    reader = csv.DictReader(data)
    for row in reader:
        if row['State']in['Jharkhand', 'Odisha', 'Andhra Pradesh','Chhattisgarh'] :
                city.append([row['City'], row['Group']])
                casualty.append([row['Killed'], row['Wounded']])

npcasualty=np.array(casualty)
npcasualty[npcasualty=='']=0
npcasualty=np.array(npcasualty,dtype=float)
npcasualty=np.sum(npcasualty,axis=1)
print(np.sum(npcasualty).astype(int))

5628


Terror City Casualty

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

Problem Statement :
Find top 5 Indian Cities which has most number of casualties ?
Print top 5 cities along with total casualties in that city. Print count of Casualty as integer value.
Note: Ignoring the City which is Unknown.
Casualty = Killed + Wounded.
Output Format :
city_1 casualty_1
city_2 casualty_2
city_3 casualty_3
city_4 casualty_4
city_5 casualty_5

In [138]:

import  numpy  as np
import csv

casualty=[]
month=[]
city=[]

with open('Datasets/Sample.csv', 'r', encoding='utf-8') as data:
    reader = csv.DictReader(data)
    for row in reader:
        if row['Country'] == 'India':
                city.append(row['City'])
                casualty.append([row['Killed'], row['Wounded']])

npcasualty=np.array(casualty)
npcity=np.array(city)
npcasualty[npcasualty=='']=0
npcasualty=np.array(npcasualty,dtype=float)
npcasualty=np.sum(npcasualty,axis=1)

np_cities = np.unique(npcity)
print(np_cities)

city_casualties = []
for i in np_cities:
    if i == 'Unknown':
        continue
    city_idx = npcity == i
    city_casualties.append(np.sum(npcasualty[city_idx]))

npcasualty = np.array(city_casualties)
index=np.argpartition(npcasualty, -5)[-5:]
for i in index:
    print(np_cities[i], ' ', npcasualty[i].astype(int))
# print(int(npcasualty[index]),npcity[index][0],npcity[index][1])



['Aankro' 'Aatpal' 'Abhapalli' ... 'runikhata' 'srinagar' 'uri']
Guwahati   822
Jammu   1119
Mumbai   2016
Srinagar   3134
New Delhi   2095


Terrorism FrequentDay

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the most frequent day of attack in a terrorismDataset ?
Note: Here np.unique can be used.
Print count of frequent day and number of attack as Integer value.
Output Format :
Day NumberOFAttack

In [8]:

import  numpy  as np
import csv

casualty=[]
day=[]

with open('Datasets/Sample.csv', 'r', encoding='utf-8') as data:
    reader = csv.DictReader(data)
    for row in reader:
        if row['Day']!='0' and row['Month'] != '0':
            day.append(row['Day'])
            casualty.append([row['Killed'], row['Wounded']])

npcasualty=np.array(casualty)
npday=np.array(day).astype(int)
npcasualty[npcasualty=='']=0
npcasualty=np.array(npcasualty,dtype=float)
npcasualty=np.sum(npcasualty,axis=1).astype(int)

dayIdx = np.unique(npday)
byDay = []
for i in dayIdx:
    idx = npday == i
    byDay.append(np.sum(npcasualty[idx]))

idx = np.argmax(byDay)
print(dayIdx[idx],' ', byDay[idx])





11   52285


In [9]:

import  numpy  as np
import csv

casualty=[]
day=[]

with open('Datasets/Sample.csv', 'r', encoding='utf-8') as data:
    reader = csv.DictReader(data)
    for row in reader:
        if row['Day']!='0' and row['Month'] != '0':
            day.append(row['Day'])

npday=np.array(day).astype(int)

dayIdx = np.unique(npday)
byDay = []
for i in dayIdx:
    idx = npday == i
    byDay.append(np.count_nonzero(npday[idx]))

idx = np.argmax(byDay)
print(dayIdx[idx],' ', byDay[idx])





15   6500
