# NumPy Arrays 1D & 2D

In [2]:
import numpy as np

a = [1, 2, 3]
b = np.array(a)

print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1, 2, 3, '5', 4, 5]
b = np.array(a, dtype = str)
print(b)

['1' '2' '3' '5' '4' '5']


In [4]:
a = [1, 2, 3, '5', 4, 5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4' '5' '1' '2' '3' '5' '4' '5' '1' '2' '3' '5' '4' '5']


### np zeros

In [5]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [7]:
b = np.zeros((2, 3), dtype = int)
print(b)

c = np.zeros((2, 3))
print(c)


[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]


### np ones

In [6]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

### np full

In [12]:
b = np.full((2, 3), 5, dtype = float)
print(b)

c = np.full((2, 3), 5)
print(c)

[[5. 5. 5.]
 [5. 5. 5.]]
[[5 5 5]
 [5 5 5]]


np empty Regresa un array sin inicializar con valores aleatorios

In [14]:
b = np.empty((2, 3))
print(b)

c = np.empty((2, 3))
print(c)

[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]
[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]


## Numpy 2D

### np.arange

In [16]:
b = np.arange(2, 20, 2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### np.linspace 
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]

Return evenly spaced numbers over a specified interval.
Returns num evenly spaced samples, calculated over the interval [start, stop].

In [24]:
b = np.linspace(2, 10, num = 4)
print(b)
print(b[1] - b[0])
print(b[3] - b[2])


[ 2.          4.66666667  7.33333333 10.        ]
2.666666666666666
2.666666666666667


### np.identity

In [25]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.eye

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)[source]


Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [26]:
b = np.eye(3, 4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### np.random.rand

In [27]:
b = np.random.rand(3)
b

array([0.5599841 , 0.02991516, 0.97522483])

### np.random.rand


In [31]:
a = np.random.rand(3)
print(a)
b = np.random.rand(2, 3)
print(b)

[0.2818014  0.56326358 0.09678695]
[[0.95770222 0.74415119 0.8105432 ]
 [0.0868493  0.12907773 0.3541841 ]]


In [32]:
b = np.random.rand(10)*10
print(b)

[3.62729942 2.67094574 9.37511014 9.2091678  1.7834752  2.58625576
 0.81401443 0.61896808 8.77108762 5.64543825]


### np.random.randint

random.randint(low, high=None, size=None, dtype=int)

Return random integers from low (inclusive) to high (exclusive).
Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [29]:
a = np.random.rand(3)
print(b)
b = np.random.rand(2, 3)
print(ab)

array([[0.05684248, 0.48540928, 0.95903838],
       [0.79646391, 0.06927303, 0.05981643]])

In [33]:
np.random.randint(5, size=(2, 4))

array([[1, 1, 1, 2],
       [3, 0, 4, 4]])

Random Integer array

Syntax for creating a random integer array ranging from 0 to 10 of size (4, 4)

In [35]:
b = np.random.randint(5, size=(2, 4))
print(b)

[[0 2 1 1]
 [4 2 1 1]]


In [36]:
np.random.randint(10, 4)

ValueError: low >= high